### ISSUE TITLE
Uncaught KeyError: 'excel_sync'


### ISSUE THREAD

**Issue by Saijin-Naib** [opengisch/shpsync#16]
Error while unloading plugin excel_sync
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "<frozen importlib._bootstrap_external>", line 1115, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1103, in _recalculate
  File "<frozen importlib._bootstrap_external>", line 1099, in _get_parent_path
KeyError: 'excel_sync'

```
excel_sync 3.4, QGIS 3.8.1-Zanzibar on Windows 10

**Comment by m-kuhn** [comment]
Can you update to the latest version?

**Comment by Saijin-Naib** [comment]
Confirmed resolved under latest plugin version.

Thanks and sorry!
