### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'fields'


### ISSUE THREAD

**Issue by saself** [opengisch/shpsync#20]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/home/saself/.local/share/QGIS/QGIS3/profiles/default/python/plugins/excel_sync/excel_sync.py", line 126, in readSettings
    self.initSyncer(settings)
  File "/home/saself/.local/share/QGIS/QGIS3/profiles/default/python/plugins/excel_sync/excel_sync.py", line 243, in initSyncer
    self.syncer = Syncer(settings)
  File "/home/saself/.local/share/QGIS/QGIS3/profiles/default/python/plugins/excel_sync/core/shp_excel_sync.py", line 145, in __init__
    self.shpKeyIdx = field_idx_from_name(self.shpName, self.shpKeyName)
  File "/home/saself/.local/share/QGIS/QGIS3/profiles/default/python/plugins/excel_sync/core/shp_excel_sync.py", line 60, in field_idx_from_name
    idx = layer_from_name(layerName).fields().indexFromName(fieldName)
AttributeError: 'NoneType' object has no attribute 'fields'

```
excel_sync 3.6, QGIS 3.18.3-Zürich on Linux 5.4.72-microsoft-standard-WSL2

**Comment by m-kuhn** [comment]
Thanks for reporting, please specify the steps to reproduce.
